### PR TITLE
Travis ci

### PR DESCRIPTION
**Pull request by tkmcmaster**
Added Travis CI integration to build and run our tests. If this works we'll remove it from github actions.

### CODE REVIEW

**Comment by EliSnow** [comment]
@tkmcmaster, what benefit will Travis CI provide over GA?

**Comment by tkmcmaster** [comment]
> 
> 
> @tkmcmaster, what benefit will Travis CI provide over GA?

GitHub Actions are not supported by the org, only TravisCI. I tried to get help with GitHub actions for our other repositories and was told it was not a supported technology and was asked why we weren't using TravisCI. All the other projects are already using TravisCI. This is our last one that isn't. As far as features, they are very similar in function.

**Comment by EliSnow** [comment]
In this particular case, since this an open source project somewhat outside
the realm of support of the internal FamilySearch platform, does it matter?
From the perspective of having an open source project which can then be
forked by any GitHub user and the CI will just work for them, I'd much
prefer pewpew stick with GA.

**Comment by tkmcmaster** [comment]
> 
> In this particular case, since this an open source project somewhat outside the realm of support of the internal FamilySearch platform, does it matter? From the perspective of having an open source project which can then be forked by any GitHub user and the CI will just work for them, I'd much prefer pewpew stick with GA.

That may be what we decide. This was more a test to see how it would work on Rust. GitHub actions are unsupported internally, but it looks like TravisCI has not be set up completely for the FamilySearch organization here on Github like the other GitHub orgs.

**Comment by tkmcmaster** [comment]
Holding off on TravisCI for now. We may revisit it in the future.

**Pull request closed without merging**
