### PR TITLE
Update dependencies20230123

### PR DESCRIPTION
**Pull request by tkmcmaster**
- [Fixed clippy warnings](https://github.com/FamilySearch/pewpew/commit/887082fde124690f53ca4c972bda8f612d0b0e2b)
- [Updated dependencies](https://github.com/FamilySearch/pewpew/commit/7518009a2ac7d088ecc3830fab0521be0ee25c79)
  - [Updated clap and base64 dependencies](https://github.com/FamilySearch/pewpew/commit/ac6a3f0edc4b1150e919a9fe8b060ec784180d51)
  - [Updated Node.js dependencies](https://github.com/FamilySearch/pewpew/commit/6ab5ac0b92ad17a60a034d8c7fb48c9bcebdfe67)
  - [Updated Chart.js dependency](https://github.com/FamilySearch/pewpew/commit/2076a306a6a504afcfe99556b5dfa7e822807cbf)
- [Fixed multiple includes on try runs](https://github.com/FamilySearch/pewpew/commit/e2311e6817e92dbbbc92fe70c020282900982754)
  - Cleaned up the start-at to only parse once
  - Fixed the multiple --include. Clap no longer allows multiple occurences, it only allows multiple passed on one occurence. See https://github.com/clap-rs/clap/issues/2688 and https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#400---2022-09-28
  - This does introduce a bug that if you specify the config file immediately after --include(s) it will think it's part of the --include. The user must either pass another option after -i or put the config file before the -i

### CODE REVIEW

**Review by summersjc — APPROVED** [review]
Assuming all tests pass looks ok

**Comment by summersjc** [comment]
Can't you add more files to this?

**Comment by tkmcmaster** [comment]
> Can't you add more files to this?

We can, but merging this doesn't release so we can create a new PR with new files. This one is just updated dependencies (and changes required by lint and updates).

**Comment by tkmcmaster** [comment]
The Windows Test Suite is hanging on a single test in Github Actions but passes running locally (on Windows).

**Pull request merged**
